-- Creating reimbursement table to store individual reimbursement data
CREATE TABLE reimbursement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    distance_driven DECIMAL(10, 2) NOT NULL
);

-- Creating receipt table to store receipt data related to a reimbursement
CREATE TABLE receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    reimbursement_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (reimbursement_id) REFERENCES reimbursement(id)
);

-- Inserting initial data
INSERT INTO reimbursement (first_name, last_name, start_date, end_date, distance_driven)
VALUES ('Andy', 'Anderson', '2022-11-10', '2022-11-15', 215.00);

INSERT INTO receipt (reimbursement_id, type, price)
VALUES (1, 'TICKET', 13.95),
       (1, 'TICKET', 13.95);