CREATE TABLE reimbursement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    distance_driven REAL
);

CREATE TABLE receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    reimbursement_id BIGINT,
    type VARCHAR(50),
    price REAL,
    FOREIGN KEY (reimbursement_id) REFERENCES reimbursement(id)
);
INSERT INTO reimbursement (first_name, last_name, start_date, end_date, distance_driven)
VALUES ('Andy', 'Anderson', '2022-11-10', '2022-11-15', 215);
INSERT INTO receipt (reimbursement_id, type, price) VALUES (1, 'ticket', 13.95);
INSERT INTO receipt (reimbursement_id, type, price) VALUES (1, 'ticket', 13.95);